name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check formatting
        run: bunx biome format

      - name: Run linter
        run: bunx biome lint

      - name: Run unit and integration tests
        run: bun test

      - name: Build
        run: bun run build

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps

      - name: Run Playwright tests
        run: bun run test:e2e

      - name: Check Playwright report directory
        if: ${{ failure() }}
        id: playwright-report-dir
        run: |
          if [ -d "playwright-report" ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload Playwright report on failure
        if: ${{ failure() && steps.playwright-report-dir.outputs.exists == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
